# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/
language: node_js
node_js:
  - 12
script:
  - npm test
  # Generate code coverage report and upload to codecov.io
  - npm run report
  - npm run build

# https://docs.travis-ci.com/user/deployment/pages/
deploy:
  provider: pages
  github_token: $GITHUB_PERSONAL_ACCESS_TOKEN # Set in the settings page of your repository, as a secure variable
  skip_cleanup: true
  local_dir: build
  on:
    branch: main
